* GLOBAL:  
    ENABLED                 =   true  
    TO_FILE                 =   true  
    TO_STANDARD_OUTPUT      =   false  
    FORMAT                  =   "[%level | %datetime] | %msg"  
    FILENAME                =   "./log/log_%datetime{%Y%M%d}.log"  
    MILLISECONDS_WIDTH      =   3  
    PERFORMANCE_TRACKING    =   true  
    MAX_LOG_FILE_SIZE       =   20971520
    LOG_FLUSH_THRESHOLD     =   0  
      
* TRACE: 
    FILENAME                =   "./log/trace_log_%datetime{%Y%M%d}.log"  
      
* DEBUG:  
    ENABLED                 =   false  
      
* FATAL:  
    ENABLED                 =   false  
      
* ERROR:  
    ENABLED                 =   false  
      
* WARNING:  
    ENABLED                 =   false  
      
* INFO:  
    ENABLED                 =   false  
      
* VERBOSE:  
    ENABLED                 =   false